name: CI
on:[pull_request]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install
        
      - name: Linting
        run: yarn lint
                
      - name: Test
        run: yarn test
        
      - name: Buld
        run: yarn build
